import { Router, type IRouter } from "express";
import { z } from "zod";
import {
  getAllCards,
  getAllCardOres,
  getOresByIds,
  insertCard,
  insertCardOres,
  uploadCardImageToSupabase,
  formatCard,
  calcRarity,
} from "../models/supabase.js";
import { generateCardIllustration } from "../services/image.service.js";
import { generateCardMeta } from "../services/ai.service.js";
import { fail, serverError } from "../utils/response.js";

const router: IRouter = Router();

const smeltSchema = z.object({
  name: z.string().optional(),
  description: z.string().default(""),
  oreIds: z.array(z.number().int().positive()).min(1, "至少需要一个矿石"),
  mode: z.enum(["A", "B", "C"]).default("A"),
});

router.get("/cards", async (req, res) => {
  try {
    const [cards, cardOres] = await Promise.all([getAllCards(), getAllCardOres()]);
    res.json(cards.map((card) => formatCard(card, cardOres)));
  } catch (err) {
    req.log.error({ err }, "Failed to get cards");
    serverError(res);
  }
});

router.post("/smelt", async (req, res) => {
  const parsed = smeltSchema.safeParse(req.body);
  if (!parsed.success) {
    fail(res, "参数错误：" + JSON.stringify(parsed.error.flatten().fieldErrors));
    return;
  }

  const { description, oreIds, mode } = parsed.data;
  const needsImage = mode === "B" || mode === "C";

  try {
    const ores = await getOresByIds(oreIds);
    if (ores.length === 0) {
      fail(res, "找不到有效的矿石，请检查矿石 ID");
      return;
    }

    const rarity = calcRarity(ores.length);

    // ── Step 1: GPT 提取动词/名词 → 生成里程碑标题 + 插图描述 ──────────────
    let milestoneTitle = parsed.data.name?.trim() || "";
    let illustrationDescription = "";

    if (needsImage) {
      try {
        const oreContents = ores.map((o) =>
          [o.title, o.content].filter(Boolean).join("："),
        );
        const cardMeta = await generateCardMeta(oreContents);
        if (!milestoneTitle) milestoneTitle = cardMeta.milestoneTitle;
        illustrationDescription = cardMeta.illustrationDescription;
        req.log.info({ milestoneTitle, illustrationDescription }, "Card meta generated by GPT");
      } catch (metaErr) {
        req.log.warn({ err: metaErr }, "GPT card meta failed, using fallback");
      }
    }

    const name = milestoneTitle || `${rarity} 卡片`;
    const card = await insertCard({ name, description, rarity });
    await insertCardOres(oreIds.map((ore_id) => ({ card_id: card.id, ore_id })));

    // ── Step 2: DALL-E 生成个性化插画 ──────────────────────────────────────
    let supabaseImageUrl: string | null = null;

    if (needsImage) {
      try {
        const fallbackDescription = ores
          .map((o) => o.title)
          .join(", ");

        const illustrationBuffer = await generateCardIllustration({
          illustrationDescription: illustrationDescription || fallbackDescription,
        });

        const uploadResult = await uploadCardImageToSupabase(illustrationBuffer, card.id);
        supabaseImageUrl = uploadResult.publicUrl;
      } catch (imgErr) {
        req.log.warn({ err: imgErr }, "Card image generation failed, card saved without image");
      }
    }

    res.status(201).json({
      cardId: card.id,
      ...formatCard(card, []),
      oreIds,
      milestoneTitle: name,
      illustrationDescription: illustrationDescription || null,
      supabaseImageUrl,
    });
  } catch (err) {
    req.log.error({ err }, "Failed to smelt card");
    serverError(res, "炼金失败，请重试");
  }
});

export default router;
